### ISSUE TITLE
Wont open "Javascript error happened in main process"

### ISSUE THREAD

**Issue by Zoerachael** [jsitor/stick-ies#26]
I need help! the App won't open all of a sudden, Tried the latest update and still didn't resolve it. 

shows error message : 

`Uncaught Exception:
Error: EPERM: operation not permitted, open '/Users/Zoe/Documents/config.json'
at Object.openSync (fs.js:476:3)
at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
at Object.readFileSync (fs.js:377:35)
at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
at ElectronStore.get store [as store] (/Applications/Stick-ies.app/Contents/Resources/app.asar/node_modules/conf/dist/source/index.js:276:29)
at new Conf (/Applications/Stick-ies.app/Contents/Resources/app.asar/node_modules/conf/dist/source/index.js:131:32)
at new ElectronStore (/Applications/Stick-ies.app/Contents/Resources/app.asar/node_modules/electron-store/index.js:69:3)
at Object.<anonymous> (/Applications/Stick-ies.app/Contents/Resources/app.asar/src/store/notes-store.js:7:13)
at Module._compile (internal/modules/cjs/loader.js:1078:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)`

**Comment by narana8898** [comment]
I have been having the same issue, is this going to be resolved anytime soon?

**Comment by ashvin777** [comment]
Is there anything changed for your guys recently, any OS updates or Any
software which could have caused this? And changes in user permissions?

It seems the app has lost access to its files due to the permissions issue.
That should not happen unless someone changes some things.


Please share belows things to help me diagnose the issue.

1. Open preferences and share the notes path visible in preferences screen
2. Share the screenshot of the Finder window of the storage path
3. Check if the folder exists with some set of app files.

**Comment by ashvin777** [comment]
Please try the latest build, we have fixed this issue.

**Comment by ashvin777** [comment]
Is it resolved ?
